### ISSUE TITLE
Having trouble understanding with an already made object

### ISSUE THREAD

**Issue by eorroe** [slikts/promiseproxy#3]
`chrome` is already an object that exists, could you make an example with an Object literal that you create yourself?

**Comment by slikts** [comment]
Thanks, the readme example really is lacking; hopefully this helps more:

``` js
// An example API with async methods
const api = {
  asyncDo: function(callback) { setTimeout(callback, 10) },
  nestedObj: {
    anotherAsyncDo: function(unusedArg, callback) { setTimeout(callback, 10) },
  },
  ignored: () => console.log('not an async method'),
}
// The schema mirrors the structure of the API, but includes only the callback methods
const schema = {
  asyncDo: 0, // asyncDo(callback) callback parameter index = 0
  nestedObj: {
    anotherAsyncDo: 1 // anotherAsyncDo(unusedArg, callback) callback parameter index = 1
  },
}
const promisified = PromiseProxy(api, schema)
promisified.asyncDo().then(callback)
// Same as...
api.asyncDo(callback)
```

**Comment by eorroe** [comment]
So this makes every method based on the Schema, it promisifies everything?

**Comment by slikts** [comment]
Everything on the schema is promisified, so `promisified.nestedObj.anotherAsyncDo()` would return a promise too; it should also be noted that the promisification happens lazily, i.e., `api.nestedObj` will be promisified only when it's accessed, so there's no upfront cost for the nested parts of the API.

**Comment by eorroe** [comment]
Oh okay now I understand interesting, will star, but have no idea for usecase as of right now.

Perhaps in node on the backend for express it'll be interesting to use.

**Comment by slikts** [comment]
The use case is that promises are a nicer way to do async programming than continuation-passing style (callbacks), since there's  things like `Promise.all()` and `async/await` and less nesting, but not all APIs support promises yet, so this is a way to add that support.
